-- =============================================================================
-- Occasion library — full global master list (277 occasions,
-- 26 categories). Replaces the prior seed.
-- occasion_id is referenced by bakery_occasions ON DELETE CASCADE; safe here
-- because no bakery has selections yet (dev). Idempotent on re-run.
-- =============================================================================
delete from public.occasion_library;
insert into public.occasion_library (name, slug, category, icon, default_enabled, sort_order) values
  ('Baby''s First Birthday', 'babys-first-birthday', 'Birthdays', 'cake', false, 0),
  ('Kids Birthday', 'kids-birthday', 'Birthdays', 'cake', true, 1),
  ('Teen Birthday', 'teen-birthday', 'Birthdays', 'cake', false, 2),
  ('Sweet 16', 'sweet-16', 'Birthdays', 'cake', true, 3),
  ('Quinceanera', 'quinceanera', 'Birthdays', 'cake', false, 4),
  ('18th Birthday', '18th-birthday', 'Birthdays', 'cake', false, 5),
  ('21st Birthday', '21st-birthday', 'Birthdays', 'cake', false, 6),
  ('Adult Birthday', 'adult-birthday', 'Birthdays', 'cake', true, 7),
  ('Milestone Birthday', 'milestone-birthday', 'Birthdays', 'cake', true, 8),
  ('Surprise Birthday', 'surprise-birthday', 'Birthdays', 'cake', false, 9),
  ('Belated Birthday', 'belated-birthday', 'Birthdays', 'cake', false, 10),
  ('Proposal', 'proposal', 'Love & Relationships', 'heart', false, 100),
  ('Engagement', 'engagement', 'Love & Relationships', 'heart', true, 101),
  ('Ring Ceremony', 'ring-ceremony', 'Love & Relationships', 'heart', false, 102),
  ('Nikah', 'nikah', 'Love & Relationships', 'heart', false, 103),
  ('Wedding', 'wedding', 'Love & Relationships', 'heart', true, 104),
  ('Wedding Reception', 'wedding-reception', 'Love & Relationships', 'heart', false, 105),
  ('Bridal Shower', 'bridal-shower', 'Love & Relationships', 'heart', true, 106),
  ('Bachelor Party', 'bachelor-party', 'Love & Relationships', 'heart', false, 107),
  ('Bachelorette Party', 'bachelorette-party', 'Love & Relationships', 'heart', false, 108),
  ('Wedding Anniversary', 'wedding-anniversary', 'Love & Relationships', 'heart', true, 109),
  ('Silver Anniversary', 'silver-anniversary', 'Love & Relationships', 'heart', false, 110),
  ('Golden Anniversary', 'golden-anniversary', 'Love & Relationships', 'heart', false, 111),
  ('Diamond Anniversary', 'diamond-anniversary', 'Love & Relationships', 'heart', false, 112),
  ('Valentine''s Day', 'valentines-day', 'Love & Relationships', 'heart', true, 113),
  ('Promise Day', 'promise-day', 'Love & Relationships', 'heart', false, 114),
  ('Rose Day', 'rose-day', 'Love & Relationships', 'heart', false, 115),
  ('Chocolate Day', 'chocolate-day', 'Love & Relationships', 'heart', false, 116),
  ('Teddy Day', 'teddy-day', 'Love & Relationships', 'heart', false, 117),
  ('Hug Day', 'hug-day', 'Love & Relationships', 'heart', false, 118),
  ('Kiss Day', 'kiss-day', 'Love & Relationships', 'heart', false, 119),
  ('Propose Day', 'propose-day', 'Love & Relationships', 'heart', false, 120),
  ('First Date Anniversary', 'first-date-anniversary', 'Love & Relationships', 'heart', false, 121),
  ('First Meeting Anniversary', 'first-meeting-anniversary', 'Love & Relationships', 'heart', false, 122),
  ('Friendship Day', 'friendship-day', 'Love & Relationships', 'heart', false, 123),
  ('Pregnancy Announcement', 'pregnancy-announcement', 'Family & Baby', 'baby', false, 200),
  ('Baby Shower', 'baby-shower', 'Family & Baby', 'baby', true, 201),
  ('Gender Reveal', 'gender-reveal', 'Family & Baby', 'baby', true, 202),
  ('Welcome Baby', 'welcome-baby', 'Family & Baby', 'baby', false, 203),
  ('Baby Naming Ceremony', 'baby-naming-ceremony', 'Family & Baby', 'baby', false, 204),
  ('Baptism', 'baptism', 'Family & Baby', 'baby', false, 205),
  ('Christening', 'christening', 'Family & Baby', 'baby', false, 206),
  ('Aqiqah', 'aqiqah', 'Family & Baby', 'baby', false, 207),
  ('Adoption Celebration', 'adoption-celebration', 'Family & Baby', 'baby', false, 208),
  ('Family Reunion', 'family-reunion', 'Family & Baby', 'baby', false, 209),
  ('Mother''s Day', 'mothers-day', 'Family & Baby', 'baby', true, 210),
  ('Father''s Day', 'fathers-day', 'Family & Baby', 'baby', true, 211),
  ('Grandparents Day', 'grandparents-day', 'Family & Baby', 'baby', false, 212),
  ('Siblings Day', 'siblings-day', 'Family & Baby', 'baby', false, 213),
  ('Graduation', 'graduation', 'Education', 'graduation-cap', true, 300),
  ('Convocation', 'convocation', 'Education', 'graduation-cap', false, 301),
  ('School Graduation', 'school-graduation', 'Education', 'graduation-cap', false, 302),
  ('College Graduation', 'college-graduation', 'Education', 'graduation-cap', false, 303),
  ('University Graduation', 'university-graduation', 'Education', 'graduation-cap', false, 304),
  ('First Day of School', 'first-day-of-school', 'Education', 'graduation-cap', false, 305),
  ('Last Day of School', 'last-day-of-school', 'Education', 'graduation-cap', false, 306),
  ('Exam Success', 'exam-success', 'Education', 'graduation-cap', false, 307),
  ('Scholarship', 'scholarship', 'Education', 'graduation-cap', false, 308),
  ('Degree Completion', 'degree-completion', 'Education', 'graduation-cap', false, 309),
  ('Teacher Appreciation', 'teacher-appreciation', 'Education', 'graduation-cap', false, 310),
  ('New Job', 'new-job', 'Career & Business', 'briefcase', true, 400),
  ('Job Promotion', 'job-promotion', 'Career & Business', 'briefcase', true, 401),
  ('Retirement', 'retirement', 'Career & Business', 'briefcase', true, 402),
  ('Work Anniversary', 'work-anniversary', 'Career & Business', 'briefcase', false, 403),
  ('Office Anniversary', 'office-anniversary', 'Career & Business', 'briefcase', false, 404),
  ('Employee of the Month', 'employee-of-the-month', 'Career & Business', 'briefcase', false, 405),
  ('Team Achievement', 'team-achievement', 'Career & Business', 'briefcase', false, 406),
  ('Business Launch', 'business-launch', 'Career & Business', 'briefcase', false, 407),
  ('Startup Launch', 'startup-launch', 'Career & Business', 'briefcase', false, 408),
  ('Shop Opening', 'shop-opening', 'Career & Business', 'briefcase', false, 409),
  ('Restaurant Opening', 'restaurant-opening', 'Career & Business', 'briefcase', false, 410),
  ('Product Launch', 'product-launch', 'Career & Business', 'briefcase', false, 411),
  ('Office Opening', 'office-opening', 'Career & Business', 'briefcase', false, 412),
  ('Office Relocation', 'office-relocation', 'Career & Business', 'briefcase', false, 413),
  ('Business Partnership', 'business-partnership', 'Career & Business', 'briefcase', false, 414),
  ('Record Sales Celebration', 'record-sales-celebration', 'Career & Business', 'briefcase', false, 415),
  ('New Car Purchase', 'new-car-purchase', 'Vehicles', 'car', false, 500),
  ('New Motorcycle Purchase', 'new-motorcycle-purchase', 'Vehicles', 'car', false, 501),
  ('New Bicycle Purchase', 'new-bicycle-purchase', 'Vehicles', 'car', false, 502),
  ('New Truck Purchase', 'new-truck-purchase', 'Vehicles', 'car', false, 503),
  ('New RV Purchase', 'new-rv-purchase', 'Vehicles', 'car', false, 504),
  ('First Car', 'first-car', 'Vehicles', 'car', false, 505),
  ('Dream Car', 'dream-car', 'Vehicles', 'car', false, 506),
  ('Driving License', 'driving-license', 'Vehicles', 'car', false, 507),
  ('Car Delivery Celebration', 'car-delivery-celebration', 'Vehicles', 'car', false, 508),
  ('Vehicle Upgrade', 'vehicle-upgrade', 'Vehicles', 'car', false, 509),
  ('Housewarming', 'housewarming', 'Home & Property', 'home', true, 600),
  ('New Home Purchase', 'new-home-purchase', 'Home & Property', 'home', false, 601),
  ('New Apartment', 'new-apartment', 'Home & Property', 'home', false, 602),
  ('New Villa', 'new-villa', 'Home & Property', 'home', false, 603),
  ('First Home', 'first-home', 'Home & Property', 'home', false, 604),
  ('Home Renovation Completed', 'home-renovation-completed', 'Home & Property', 'home', false, 605),
  ('Farm Purchase', 'farm-purchase', 'Home & Property', 'home', false, 606),
  ('Office Purchase', 'office-purchase', 'Home & Property', 'home', false, 607),
  ('Land Purchase', 'land-purchase', 'Home & Property', 'home', false, 608),
  ('Property Investment Celebration', 'property-investment-celebration', 'Home & Property', 'home', false, 609),
  ('Moving Into New Home', 'moving-into-new-home', 'Home & Property', 'home', false, 610),
  ('First Salary', 'first-salary', 'Financial Milestones', 'banknote', false, 700),
  ('Salary Increase', 'salary-increase', 'Financial Milestones', 'banknote', false, 701),
  ('Bonus Celebration', 'bonus-celebration', 'Financial Milestones', 'banknote', false, 702),
  ('Investment Success', 'investment-success', 'Financial Milestones', 'banknote', false, 703),
  ('Business Profit', 'business-profit', 'Financial Milestones', 'banknote', false, 704),
  ('Debt-Free Celebration', 'debt-free-celebration', 'Financial Milestones', 'banknote', false, 705),
  ('Loan Approval', 'loan-approval', 'Financial Milestones', 'banknote', false, 706),
  ('Mortgage Approval', 'mortgage-approval', 'Financial Milestones', 'banknote', false, 707),
  ('Lottery Win', 'lottery-win', 'Financial Milestones', 'banknote', false, 708),
  ('Prize Money Celebration', 'prize-money-celebration', 'Financial Milestones', 'banknote', false, 709),
  ('Award Ceremony', 'award-ceremony', 'Achievements', 'trophy', false, 800),
  ('Competition Winner', 'competition-winner', 'Achievements', 'trophy', false, 801),
  ('Sports Championship', 'sports-championship', 'Achievements', 'trophy', false, 802),
  ('Marathon Completion', 'marathon-completion', 'Achievements', 'trophy', false, 803),
  ('Fitness Transformation', 'fitness-transformation', 'Achievements', 'trophy', false, 804),
  ('Weight Loss Goal', 'weight-loss-goal', 'Achievements', 'trophy', false, 805),
  ('Personal Record', 'personal-record', 'Achievements', 'trophy', false, 806),
  ('Guinness Record', 'guinness-record', 'Achievements', 'trophy', false, 807),
  ('Certification Earned', 'certification-earned', 'Achievements', 'trophy', false, 808),
  ('Skill Achievement', 'skill-achievement', 'Achievements', 'trophy', false, 809),
  ('Graduation with Honors', 'graduation-with-honors', 'Achievements', 'trophy', false, 810),
  ('Visa Approval', 'visa-approval', 'Travel & Immigration', 'plane', false, 900),
  ('Citizenship Ceremony', 'citizenship-ceremony', 'Travel & Immigration', 'plane', false, 901),
  ('Passport Received', 'passport-received', 'Travel & Immigration', 'plane', false, 902),
  ('Immigration Success', 'immigration-success', 'Travel & Immigration', 'plane', false, 903),
  ('Study Abroad', 'study-abroad', 'Travel & Immigration', 'plane', false, 904),
  ('Return Home', 'return-home', 'Travel & Immigration', 'plane', false, 905),
  ('Welcome Home', 'welcome-home', 'Travel & Immigration', 'plane', false, 906),
  ('World Tour Completion', 'world-tour-completion', 'Travel & Immigration', 'plane', false, 907),
  ('Vacation Celebration', 'vacation-celebration', 'Travel & Immigration', 'plane', false, 908),
  ('Gaming Tournament Win', 'gaming-tournament-win', 'Gaming & Entertainment', 'gamepad-2', false, 1000),
  ('Esports Championship', 'esports-championship', 'Gaming & Entertainment', 'gamepad-2', false, 1001),
  ('Streaming Milestone', 'streaming-milestone', 'Gaming & Entertainment', 'gamepad-2', false, 1002),
  ('YouTube Subscriber Milestone', 'youtube-subscriber-milestone', 'Gaming & Entertainment', 'gamepad-2', false, 1003),
  ('Instagram Followers Milestone', 'instagram-followers-milestone', 'Gaming & Entertainment', 'gamepad-2', false, 1004),
  ('TikTok Followers Milestone', 'tiktok-followers-milestone', 'Gaming & Entertainment', 'gamepad-2', false, 1005),
  ('Twitch Milestone', 'twitch-milestone', 'Gaming & Entertainment', 'gamepad-2', false, 1006),
  ('Podcast Launch', 'podcast-launch', 'Gaming & Entertainment', 'gamepad-2', false, 1007),
  ('Album Release', 'album-release', 'Gaming & Entertainment', 'gamepad-2', false, 1008),
  ('Movie Release Party', 'movie-release-party', 'Gaming & Entertainment', 'gamepad-2', false, 1009),
  ('Book Launch', 'book-launch', 'Gaming & Entertainment', 'gamepad-2', false, 1010),
  ('New Car', 'new-car', 'Shopping & Lifestyle', 'shopping-bag', false, 1100),
  ('New Bike', 'new-bike', 'Shopping & Lifestyle', 'shopping-bag', false, 1101),
  ('New Phone', 'new-phone', 'Shopping & Lifestyle', 'shopping-bag', false, 1102),
  ('New Laptop', 'new-laptop', 'Shopping & Lifestyle', 'shopping-bag', false, 1103),
  ('New Gaming PC', 'new-gaming-pc', 'Shopping & Lifestyle', 'shopping-bag', false, 1104),
  ('New Gaming Console', 'new-gaming-console', 'Shopping & Lifestyle', 'shopping-bag', false, 1105),
  ('New Camera', 'new-camera', 'Shopping & Lifestyle', 'shopping-bag', false, 1106),
  ('New Watch', 'new-watch', 'Shopping & Lifestyle', 'shopping-bag', false, 1107),
  ('Luxury Purchase', 'luxury-purchase', 'Shopping & Lifestyle', 'shopping-bag', false, 1108),
  ('Jewelry Purchase', 'jewelry-purchase', 'Shopping & Lifestyle', 'shopping-bag', false, 1109),
  ('Designer Bag Purchase', 'designer-bag-purchase', 'Shopping & Lifestyle', 'shopping-bag', false, 1110),
  ('Dream Purchase', 'dream-purchase', 'Shopping & Lifestyle', 'shopping-bag', false, 1111),
  ('Shopping Celebration', 'shopping-celebration', 'Shopping & Lifestyle', 'shopping-bag', false, 1112),
  ('Pet Birthday', 'pet-birthday', 'Pets', 'paw-print', false, 1200),
  ('Pet Adoption Day', 'pet-adoption-day', 'Pets', 'paw-print', false, 1201),
  ('Pet Gotcha Day', 'pet-gotcha-day', 'Pets', 'paw-print', false, 1202),
  ('New Pet Welcome', 'new-pet-welcome', 'Pets', 'paw-print', false, 1203),
  ('Pet Competition Winner', 'pet-competition-winner', 'Pets', 'paw-print', false, 1204),
  ('Christmas', 'christmas', 'Christian Celebrations', 'church', true, 1300),
  ('Christmas Eve', 'christmas-eve', 'Christian Celebrations', 'church', false, 1301),
  ('Easter', 'easter', 'Christian Celebrations', 'church', true, 1302),
  ('Palm Sunday', 'palm-sunday', 'Christian Celebrations', 'church', false, 1303),
  ('Good Friday Gathering', 'good-friday-gathering', 'Christian Celebrations', 'church', false, 1304),
  ('First Communion', 'first-communion', 'Christian Celebrations', 'church', false, 1305),
  ('Confirmation', 'confirmation', 'Christian Celebrations', 'church', false, 1306),
  ('Church Anniversary', 'church-anniversary', 'Christian Celebrations', 'church', false, 1308),
  ('Eid al-Fitr', 'eid-al-fitr', 'Islamic Celebrations', 'moon', true, 1400),
  ('Eid al-Adha', 'eid-al-adha', 'Islamic Celebrations', 'moon', true, 1401),
  ('Ramadan Iftar', 'ramadan-iftar', 'Islamic Celebrations', 'moon', false, 1402),
  ('Ramadan Completion', 'ramadan-completion', 'Islamic Celebrations', 'moon', false, 1403),
  ('Islamic New Year', 'islamic-new-year', 'Islamic Celebrations', 'moon', false, 1404),
  ('Mawlid', 'mawlid', 'Islamic Celebrations', 'moon', false, 1405),
  ('Diwali', 'diwali', 'Hindu Celebrations', 'flame', true, 1500),
  ('Holi', 'holi', 'Hindu Celebrations', 'flame', true, 1501),
  ('Raksha Bandhan', 'raksha-bandhan', 'Hindu Celebrations', 'flame', false, 1502),
  ('Bhai Dooj', 'bhai-dooj', 'Hindu Celebrations', 'flame', false, 1503),
  ('Karwa Chauth', 'karwa-chauth', 'Hindu Celebrations', 'flame', false, 1504),
  ('Navratri', 'navratri', 'Hindu Celebrations', 'flame', false, 1505),
  ('Dussehra', 'dussehra', 'Hindu Celebrations', 'flame', false, 1506),
  ('Ganesh Chaturthi', 'ganesh-chaturthi', 'Hindu Celebrations', 'flame', false, 1507),
  ('Janmashtami', 'janmashtami', 'Hindu Celebrations', 'flame', false, 1508),
  ('Pongal', 'pongal', 'Hindu Celebrations', 'flame', false, 1509),
  ('Onam', 'onam', 'Hindu Celebrations', 'flame', false, 1510),
  ('Makar Sankranti', 'makar-sankranti', 'Hindu Celebrations', 'flame', false, 1511),
  ('Ugadi', 'ugadi', 'Hindu Celebrations', 'flame', false, 1512),
  ('Gudi Padwa', 'gudi-padwa', 'Hindu Celebrations', 'flame', false, 1513),
  ('Hanukkah', 'hanukkah', 'Jewish Celebrations', 'star', true, 1600),
  ('Passover', 'passover', 'Jewish Celebrations', 'star', false, 1601),
  ('Purim', 'purim', 'Jewish Celebrations', 'star', false, 1602),
  ('Rosh Hashanah', 'rosh-hashanah', 'Jewish Celebrations', 'star', false, 1603),
  ('Bar Mitzvah', 'bar-mitzvah', 'Jewish Celebrations', 'star', false, 1604),
  ('Bat Mitzvah', 'bat-mitzvah', 'Jewish Celebrations', 'star', false, 1605),
  ('Vesak', 'vesak', 'Buddhist Celebrations', 'lotus', false, 1700),
  ('Buddha Purnima', 'buddha-purnima', 'Buddhist Celebrations', 'lotus', false, 1701),
  ('Kathina', 'kathina', 'Buddhist Celebrations', 'lotus', false, 1702),
  ('New Year''s Day', 'new-years-day', 'International Holidays', 'globe', true, 1800),
  ('Lunar New Year', 'lunar-new-year', 'International Holidays', 'globe', false, 1801),
  ('Chinese New Year', 'chinese-new-year', 'International Holidays', 'globe', true, 1802),
  ('Halloween', 'halloween', 'International Holidays', 'globe', true, 1803),
  ('Thanksgiving', 'thanksgiving', 'International Holidays', 'globe', true, 1804),
  ('St. Patrick''s Day', 'st-patricks-day', 'International Holidays', 'globe', false, 1805),
  ('Mardi Gras', 'mardi-gras', 'International Holidays', 'globe', false, 1806),
  ('Carnival', 'carnival', 'International Holidays', 'globe', false, 1807),
  ('Oktoberfest', 'oktoberfest', 'International Holidays', 'globe', false, 1808),
  ('Kwanzaa', 'kwanzaa', 'International Holidays', 'globe', false, 1809),
  ('Boxing Day', 'boxing-day', 'International Holidays', 'globe', false, 1810),
  ('Independence Day', 'independence-day', 'National Celebrations', 'flag', false, 1900),
  ('Republic Day', 'republic-day', 'National Celebrations', 'flag', false, 1901),
  ('National Day', 'national-day', 'National Celebrations', 'flag', false, 1902),
  ('Cultural Festival', 'cultural-festival', 'National Celebrations', 'flag', false, 1903),
  ('Heritage Day', 'heritage-day', 'National Celebrations', 'flag', false, 1904),
  ('Community Festival', 'community-festival', 'National Celebrations', 'flag', false, 1905),
  ('Congratulations', 'congratulations', 'Social Celebrations', 'party-popper', true, 2000),
  ('Thank You', 'thank-you', 'Social Celebrations', 'party-popper', false, 2001),
  ('Good Luck', 'good-luck', 'Social Celebrations', 'party-popper', false, 2002),
  ('Farewell', 'farewell', 'Social Celebrations', 'party-popper', true, 2004),
  ('Reunion', 'reunion', 'Social Celebrations', 'party-popper', false, 2005),
  ('Surprise Party', 'surprise-party', 'Social Celebrations', 'party-popper', false, 2006),
  ('Get Well Soon', 'get-well-soon', 'Social Celebrations', 'party-popper', true, 2007),
  ('Recovery Celebration', 'recovery-celebration', 'Social Celebrations', 'party-popper', false, 2008),
  ('Retirement Party', 'retirement-party', 'Social Celebrations', 'party-popper', false, 2009),
  ('Promotion Party', 'promotion-party', 'Social Celebrations', 'party-popper', false, 2010),
  ('Neighbor Welcome', 'neighbor-welcome', 'Social Celebrations', 'party-popper', false, 2011),
  ('Charity Event', 'charity-event', 'Social Celebrations', 'party-popper', false, 2012),
  ('Volunteer Appreciation', 'volunteer-appreciation', 'Social Celebrations', 'party-popper', false, 2013),
  ('1K Followers', '1k-followers', 'Digital Milestones', 'trending-up', false, 2100),
  ('10K Followers', '10k-followers', 'Digital Milestones', 'trending-up', false, 2101),
  ('100K Followers', '100k-followers', 'Digital Milestones', 'trending-up', false, 2102),
  ('1 Million Followers', '1-million-followers', 'Digital Milestones', 'trending-up', false, 2103),
  ('YouTube Silver Play Button', 'youtube-silver-play-button', 'Digital Milestones', 'trending-up', false, 2104),
  ('YouTube Gold Play Button', 'youtube-gold-play-button', 'Digital Milestones', 'trending-up', false, 2105),
  ('Business Website Launch', 'business-website-launch', 'Digital Milestones', 'trending-up', false, 2106),
  ('Mobile App Launch', 'mobile-app-launch', 'Digital Milestones', 'trending-up', false, 2107),
  ('First Online Sale', 'first-online-sale', 'Digital Milestones', 'trending-up', false, 2108),
  ('First Customer', 'first-customer', 'Digital Milestones', 'trending-up', false, 2109),
  ('Online Store Launch', 'online-store-launch', 'Digital Milestones', 'trending-up', false, 2110),
  ('First House', 'first-house', 'Personal Milestones', 'sparkles', false, 2201),
  ('First Bike', 'first-bike', 'Personal Milestones', 'sparkles', false, 2203),
  ('First Passport', 'first-passport', 'Personal Milestones', 'sparkles', false, 2204),
  ('First Flight', 'first-flight', 'Personal Milestones', 'sparkles', false, 2205),
  ('First Solo Trip', 'first-solo-trip', 'Personal Milestones', 'sparkles', false, 2206),
  ('First Marathon', 'first-marathon', 'Personal Milestones', 'sparkles', false, 2207),
  ('First Business', 'first-business', 'Personal Milestones', 'sparkles', false, 2208),
  ('First Investment', 'first-investment', 'Personal Milestones', 'sparkles', false, 2209),
  ('First Child', 'first-child', 'Personal Milestones', 'sparkles', false, 2210),
  ('First Grandchild', 'first-grandchild', 'Personal Milestones', 'sparkles', false, 2211),
  ('First Promotion', 'first-promotion', 'Personal Milestones', 'sparkles', false, 2212),
  ('First Published Book', 'first-published-book', 'Personal Milestones', 'sparkles', false, 2213),
  ('First Concert', 'first-concert', 'Personal Milestones', 'sparkles', false, 2214),
  ('Dream Achieved', 'dream-achieved', 'Personal Milestones', 'sparkles', false, 2215),
  ('Bucket List Completed', 'bucket-list-completed', 'Personal Milestones', 'sparkles', false, 2216),
  ('Spring Celebration', 'spring-celebration', 'Seasonal Celebrations', 'sun', false, 2300),
  ('Summer Party', 'summer-party', 'Seasonal Celebrations', 'sun', false, 2301),
  ('Autumn Festival', 'autumn-festival', 'Seasonal Celebrations', 'sun', false, 2302),
  ('Winter Celebration', 'winter-celebration', 'Seasonal Celebrations', 'sun', false, 2303),
  ('Beach Party', 'beach-party', 'Seasonal Celebrations', 'sun', false, 2304),
  ('BBQ Party', 'bbq-party', 'Seasonal Celebrations', 'sun', false, 2305),
  ('Picnic Party', 'picnic-party', 'Seasonal Celebrations', 'sun', false, 2306),
  ('Garden Party', 'garden-party', 'Seasonal Celebrations', 'sun', false, 2307),
  ('Pool Party', 'pool-party', 'Seasonal Celebrations', 'sun', false, 2308),
  ('Camping Trip', 'camping-trip', 'Seasonal Celebrations', 'sun', false, 2309),
  ('Yacht Purchase', 'yacht-purchase', 'Luxury Celebrations', 'gem', false, 2400),
  ('Private Jet Purchase', 'private-jet-purchase', 'Luxury Celebrations', 'gem', false, 2401),
  ('Luxury Watch Purchase', 'luxury-watch-purchase', 'Luxury Celebrations', 'gem', false, 2402),
  ('Luxury Car Delivery', 'luxury-car-delivery', 'Luxury Celebrations', 'gem', false, 2403),
  ('Mansion Purchase', 'mansion-purchase', 'Luxury Celebrations', 'gem', false, 2404),
  ('High-End Fashion Purchase', 'high-end-fashion-purchase', 'Luxury Celebrations', 'gem', false, 2405),
  ('Art Collection Purchase', 'art-collection-purchase', 'Luxury Celebrations', 'gem', false, 2406),
  ('Surprise Gift', 'surprise-gift', 'Just Because', 'gift', false, 2500),
  ('Random Celebration', 'random-celebration', 'Just Because', 'gift', false, 2501),
  ('Appreciation Cake', 'appreciation-cake', 'Just Because', 'gift', false, 2502),
  ('Self-Love Celebration', 'self-love-celebration', 'Just Because', 'gift', false, 2503),
  ('Family Dinner', 'family-dinner', 'Just Because', 'gift', false, 2504),
  ('Friends Reunion', 'friends-reunion', 'Just Because', 'gift', false, 2505),
  ('Weekend Party', 'weekend-party', 'Just Because', 'gift', false, 2506),
  ('Friday Night Party', 'friday-night-party', 'Just Because', 'gift', false, 2507),
  ('Success Celebration', 'success-celebration', 'Just Because', 'gift', false, 2508),
  ('Happiness Celebration', 'happiness-celebration', 'Just Because', 'gift', false, 2509),
  ('Just Because Cake', 'just-because-cake', 'Just Because', 'gift', false, 2510)
on conflict (slug) do update set
  name = excluded.name, category = excluded.category, icon = excluded.icon,
  default_enabled = excluded.default_enabled, sort_order = excluded.sort_order, is_active = true;
